M48
; DRILL file {KiCad (7.0.0)} date Sat May 27 10:46:10 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-27T10:46:10+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0630
%
G90
G05
T1
X4.5192Y-3.274
X4.7382Y-3.212
T2
X5.1718Y-2.8661
X5.3085Y-2.7244
T3
X4.0906Y-3.252
X4.1229Y-3.018
T0
M30
