M48
; DRILL file {KiCad (7.0.0)} date Sat May 27 11:40:33 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-27T11:40:33+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0827
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0984
%
G90
G05
T1
X1.3276Y-2.422
X1.4791Y-2.4652
T2
X1.3016Y-3.1616
T3
X1.4589Y-3.4949
T0
M30
